# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fdilm94CR8OFtyzGGdFHnArLO2_pmsh3
"""

import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

df.head()

# Importer les librairies nécessaires
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Charger le jeu de données Iris
from sklearn.datasets import load_iris
iris = load_iris()

# Créer un DataFrame
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

# Afficher les 5 premières lignes
print("Aperçu des données :")
display(df.head())

# Informations générales
print("Informations générales :")
df.info()

# Statistiques descriptives
print("Statistiques descriptives :")
display(df.describe())

# Distribution des variables
plt.figure(figsize=(12,6))
sns.histplot(df, kde=True)
plt.title("Distribution des caractéristiques de l'Iris")
plt.show()

# Boxplots pour détecter les outliers
plt.figure(figsize=(12,6))
sns.boxplot(data=df, orient="h")
plt.title("Boxplot des caractéristiques")
plt.show()

# Visualisation des relations entre variables
sns.pairplot(df, hue="species", markers=["o", "s", "D"])
plt.suptitle("Pairplot des caractéristiques selon l'espèce", y=1.02)
plt.show()

# Matrice de corrélation
corr = df.iloc[:, :-1].corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Matrice de corrélation")
plt.show()

# Compte rendu simple
print("Compte rendu simple :")
for species in df['species'].unique():
    print(f"\nEspèce : {species}")
    display(df[df['species'] == species].describe())